apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sc-pvc
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: my-sc-example
  resources:
    requests:
      storage: 32Gi # 如果 StorageClass 中定義 Premium_LRSSKU，則最小必須為 100Gi