apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi
  # 也可以用選擇器來指定要使用的 PV
  # selector:
  #   matchLabels:
  #     release: "stable"
  #   matchExpressions:
  #     - key: environment
  #       operator: In
  #       values:
  #         - production
  #         - qa
  #         - staging
 