version: '3.8'
services:
  myrabbitmq:
    image: rabbitmq:3-management
    hostname: ${RABBITMQ_HOSTNAME}
    restart: always
    ports:
      - "8888:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      start_period: 10s
      interval: 30s
      timeout: 30s
      retries: 3
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    networks:
      - net-mq
  publisher:
    # build: ./Publisher/
    image: dog830228/mq_poc-publisher
    environment:
      - QUEUENAME=${QUEUENAME}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
    depends_on:
      myrabbitmq:
        condition: service_healthy
    networks:
      - net-mq
  workersample:
    build: ./
    #image: dog830228/mq_poc-nodeworker
    environment:
      - QUEUENAME=${QUEUENAME}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - POOL_TYPE=1
      - DBConnection=Data Source=sqlserver;Initial Catalog=orleans;User ID=sa;Password=test.123;
    depends_on:
      - publisher
    networks:
      - net-mq
  sqlserver:
    image: dog830228/silo-db:1.1
    hostname: sqlsever
    ports:
      - "1433:1433"
    restart: always
    networks:
      - net-mq
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'test.123'
      MSSQL_PID: 'Standard'

  siloweb:
    #build: ./MQDashBoard/Silo/
    image: dog830228/silo-server:1.1
    ports:
      - "8899:8899"
    expose:
      - "8899"
    restart: always
    environment:
      DBConnection: 'Data Source=sqlserver;Initial Catalog=orleans;User ID=sa;Password=test.123;'
    networks:
      - net-mq
    depends_on:
      - sqlserver
networks:
  net-mq:
    driver: bridge




