kind: StorageClass
apiVersion: storage.k8s.io/v1 
metadata:
  name: my-sc-example
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sc-pvc
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: my-sc-example
  resources:
    requests:
      storage: 32Gi 