apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be
  # mountOptions:
  #   - dir_mode=0777
  #   - file_mode=0777
  #   - uid=0
  #   - gid=0
  #   - mfsymlinks
  #   - cache=strict  # https://linux.die.net/man/8/mount.cifs
  #   - nosharesock  # reduce probability of reconnect race
  #   - actimeo=30  # reduce latency for metadata-heavy workload
  #   - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/920c2ea4-4af8-4dfe-812d-b5070befb952/resourcegroups/my-aks-dd_group/providers/Microsoft.Compute/disks/aks-pv-disk
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # 也可以用選擇器來指定要使用的 PV
  # selector:
  #   matchLabels:
  #     release: "stable"
  #   matchExpressions:
  #     - key: environment
  #       operator: In
  #       values:
  #         - production
  #         - qa
  #         - staging
